qualiclip:
  build:
    tags: 
      - "qualiclip:main"
  container_name: qualiclip
  network_mode: host
  runtime: nvidia
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
